import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(web, "packages/nac-presentation/dist");
const types = path.join(output, "types");
async function rewrite(directory) {
  for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) await rewrite(file);
    else if (entry.name.endsWith(".d.ts")) {
      let source = await fs.readFile(file, "utf8");
      source = source.replace(/(["'])@\/([^"']+)\1/g, (_match, quote, suffix) => {
        const relative = path
          .relative(directory, path.join(types, "src", suffix))
          .split(path.sep)
          .join("/");
        return quote + (relative.startsWith(".") ? relative : "./" + relative) + quote;
      });
      source = source.replace(/^import ["'][^"']+\.css["'];\n/gm, "");
      source = source.replace(/[\t ]+$/gm, "");
      await fs.writeFile(file, source);
    }
  }
}
await rewrite(types);
await fs.writeFile(
  path.join(output, "index.d.ts"),
  '// @generated by the presentation build.\nexport * from "./types/packages/nac-presentation/entry.js";\n',
);
