#!/usr/bin/env python3
"""
Generate plain-CSS semantic utilities from ArceeFM's tailwind.config.js.

Why: ArceeFM's design tokens have *different values per CSS property* for the
same suffix (e.g. `accent-primary` differs across bg/text/border), which a single
Tailwind v4 `@theme --color-*` namespace would flatten. Emitting explicit CSS
classes (with hover/focus/active/disabled variants) reproduces the exact token
values 1:1, works fully offline, and needs no build step. Tailwind's browser
build still provides all the generic utilities (grid, flex, spacing, rounded…).

Usage:
  python3 gen-semantic-css.py \
    /path/to/ArceeFM/frontend/tailwind.config.js \
    /path/to/nac/crates/nac-server/assets/app/theme/semantic.css
"""
import re
import sys

# section name in config -> (class prefix, css property, emit-variants?)
SECTIONS = {
    "backgroundColor": ("bg", "background-color", True),
    "textColor": ("text", "color", True),
    "borderColor": ("border", "border-color", True),
    "fill": ("fill", "fill", True),
    "boxShadow": ("shadow", "box-shadow", False),
}

VARIANTS = [
    ("", ""),
    ("hover\\:", ":hover"),
    ("focus\\:", ":focus"),
    ("active\\:", ":active"),
    ("disabled\\:", ":disabled"),
]

ENTRY_RE = re.compile(r'^\s*(?:"([^"]+)"|([A-Za-z0-9_-]+))\s*:\s*"([^"]+)"\s*,?\s*$')


def extract_section(text: str, name: str) -> str:
    """Return the body between `name: {` and its matching closing brace."""
    start = text.find(name + ": {")
    if start == -1:
        return ""
    i = text.find("{", start)
    depth = 0
    for j in range(i, len(text)):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1 : j]
    return ""


def emit(prefix: str, prop: str, key: str, value: str, variants: bool) -> str:
    out = []
    combos = VARIANTS if variants else VARIANTS[:1]
    for esc, pseudo in combos:
        cls = f".{esc}{prefix}-{key}{pseudo}"
        out.append(f"{cls} {{ {prop}: {value}; }}")
    return "\n".join(out)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src, encoding="utf-8").read()
    blocks = [
        "/* AUTO-GENERATED by docs/frontend-react-migration/tools/gen-semantic-css.py",
        "   Source: ArceeFM/frontend/tailwind.config.js. Do not edit by hand. */",
        "",
    ]
    total = 0
    for name, (prefix, prop, variants) in SECTIONS.items():
        body = extract_section(text, name)
        if not body:
            continue
        blocks.append(f"/* --- {name} -> .{prefix}-* --- */")
        for line in body.splitlines():
            m = ENTRY_RE.match(line)
            if not m:
                continue
            key = m.group(1) or m.group(2)
            value = m.group(3)
            blocks.append(emit(prefix, prop, key, value, variants))
            total += 1
        blocks.append("")

    # Brand ramp (colors.brand) across bg/text/border/fill
    brand_body = extract_section(text, "brand")
    if brand_body:
        blocks.append("/* --- colors.brand -> bg/text/border/fill-brand-* --- */")
        for line in brand_body.splitlines():
            m = ENTRY_RE.match(line)
            if not m:
                continue
            key = m.group(1) or m.group(2)
            value = m.group(3)
            for prefix, prop in (
                ("bg", "background-color"),
                ("text", "color"),
                ("border", "border-color"),
                ("fill", "fill"),
            ):
                blocks.append(emit(prefix, prop, f"brand-{key}", value, True))
                total += 1
        blocks.append("")

    open(dst, "w", encoding="utf-8").write("\n".join(blocks) + "\n")
    print(f"wrote {dst} ({total} token entries)")


if __name__ == "__main__":
    main()
