// @generated by ../../../scripts/generate-api-types.mjs from ../../../openapi.json.
// Do not edit by hand. Run `make generate-api-contract` from the repository root.

export interface components {
  schemas: {
    ActiveCompactionSnapshot: {
      client_id?: null | components["schemas"]["SessionClientId"];
      compaction_id: string;
      started_at_epoch_ms: number;
    };
    ActiveRunSnapshot: {
      client_id?: null | components["schemas"]["SessionClientId"];
      prompt_preview: string;
      run_id: components["schemas"]["SessionRunId"];
      started_at_epoch_ms: number;
      submitted_user_message?: null | components["schemas"]["SubmittedUserMessageSnapshot"];
    };
    AgentEvent:
      | { prompt_preview: string; thread_name?: string | null; type: "run_started" }
      | { iteration: number; thread_name?: string | null; type: "model_call_started" }
      | {
          thread_name?: string | null;
          type: "token_usage_updated";
          usage: components["schemas"]["TokenUsage"];
        }
      | {
          args_detail?: string | null;
          args_preview: string;
          call_id: string;
          key_arg_preview?: string | null;
          name: string;
          thread_name?: string | null;
          type: "tool_call_started";
        }
      | {
          call_id: string;
          cleanup_duration_ms?: number | null;
          command_status?: null | components["schemas"]["CommandStatus"];
          completion_status?: null | components["schemas"]["ToolCompletionStatus"];
          content_preview: string;
          effective_timeout_ms?: number | null;
          execution_duration_ms?: number | null;
          exit_code?: number | null;
          is_error: boolean;
          name: string;
          remote_outcome_uncertain?: boolean;
          thread_name?: string | null;
          type: "tool_call_finished";
        }
      | { action: string; name: string; source_threads: string[]; type: "thread_started" }
      | { line: string; name: string; type: "thread_log" }
      | {
          instruction_preview: string;
          name: string;
          steering_id: number;
          type: "thread_steering_queued";
        }
      | {
          instruction_preview: string;
          name: string;
          steering_id: number;
          type: "thread_steering_delivered";
        }
      | {
          instruction_preview: string;
          name: string;
          steering_id: number;
          type: "thread_steering_expired";
        }
      | { instruction_preview: string; steering_id: number; type: "orchestrator_steering_queued" }
      | {
          instruction_preview: string;
          steering_id: number;
          type: "orchestrator_steering_delivered";
        }
      | { instruction_preview: string; steering_id: number; type: "orchestrator_steering_expired" }
      | {
          compaction_id: string;
          reason: components["schemas"]["CompactionReason"];
          type: "orchestrator_compaction_started";
        }
      | {
          compaction_id: string;
          reason: components["schemas"]["CompactionReason"];
          type: "orchestrator_compaction_completed";
        }
      | {
          cause: components["schemas"]["CompactionSkipReason"];
          compaction_id: string;
          reason: components["schemas"]["CompactionReason"];
          type: "orchestrator_compaction_skipped";
        }
      | {
          compaction_id: string;
          failure: components["schemas"]["CompactionFailure"];
          reason: components["schemas"]["CompactionReason"];
          type: "orchestrator_compaction_failed";
        }
      | {
          exit_code: number;
          name: string;
          timed_out: boolean;
          timeout_reason?: string | null;
          type: "thread_finished";
          usage?: null | components["schemas"]["TokenUsage"];
        }
      | {
          content: string;
          thread_name?: string | null;
          type: "assistant_message";
          usage?: null | components["schemas"]["TokenUsage"];
        }
      | { message: string; thread_name?: string | null; type: "error" }
      | {
          reason: string;
          server_name: string;
          thread_name?: string | null;
          type: "mcp_server_skipped";
        }
      | {
          kind: components["schemas"]["McpNotificationKind"];
          message: string;
          server_name: string;
          thread_name?: string | null;
          type: "mcp_notification";
        }
      | { message: string; thread_name?: string | null; type: "model_error" }
      | { thread_name?: string | null; type: "run_finished" };
    AssistantStreamDelta: {
      reasoning?: string | null;
      reset?: boolean;
      retry_attempt?: number | null;
      text?: string | null;
      thread_name?: string | null;
    };
    BackendKind:
      | "deepseek-chat"
      | "fireworks-chat"
      | "together-chat"
      | "openai-responses"
      | "openai-chat-completions"
      | "chatgpt-codex-responses"
      | "anthropic-messages"
      | "arcee-auth"
      | "arcee-api";
    ChangedFileStat: {
      additions?: number | null;
      deletions?: number | null;
      path: string;
      status: string;
    };
    CommandStatus: "completed" | "timed_out" | "cancelled" | "spawn_error";
    CompactionFailure:
      | "summary_request_failed"
      | "summary_rejected"
      | "checkpoint_persistence_failed"
      | "cancelled";
    CompactionReason: "auto" | "manual";
    CompactionSkipReason: "no_eligible_boundary" | "already_compacted";
    EpisodeSnapshot: {
      action: string;
      content: string;
      created_at: string;
      id: number;
      session_id: string;
      status: components["schemas"]["EpisodeStatus"];
      thread_name: string;
    };
    EpisodeStatus: "ok" | "error" | "timed_out" | "cancelled";
    FunctionCall: { arguments: string; name: string };
    LaggedEvent: { missed: number };
    McpNotificationKind:
      | "catalog_refreshed"
      | "catalog_refresh_failed"
      | "resource_updated"
      | "log"
      | "progress"
      | "subscription_ended";
    Message:
      | { content: string; role: "system" }
      | { content: string; role: "user" }
      | {
          content: string | null;
          duration_ms?: number | null;
          model_origin?: null | components["schemas"]["ModelOrigin"];
          reasoning_details?: unknown;
          reasoning_field?: string | null;
          reasoning_text?: string | null;
          role: "assistant";
          tool_calls?: components["schemas"]["ToolCall"][] | null;
        }
      | { content: components["schemas"]["ToolContentSchema"]; role: "tool"; tool_call_id: string };
    MessageCycleMetadata: { marker: string; thread_names: string[] };
    MessagePageMetadata: { end: number; has_older: boolean; start: number; total: number };
    ModelOrigin: { backend: components["schemas"]["BackendKind"]; model: string };
    PartialModelOutput: { reasoning?: boolean; text?: boolean; tool_call?: boolean };
    PermissionApprovalMode: "manual" | "auto_approve";
    PermissionReply: "once" | "always" | "reject";
    PermissionRequest: {
      call_id?: string | null;
      created_at_epoch_ms: number;
      id: string;
      resources: components["schemas"]["PermissionRequestResource"][];
      session_id: string;
      tool: string;
    };
    PermissionRequestResource: {
      action: string;
      display: string;
      resource: string;
      save_resource?: string | null;
    };
    ReadinessCheck: { detail: string; name: string; ready: boolean };
    ReadinessResponse: {
      build_id: string;
      build_track: string;
      checks: components["schemas"]["ReadinessCheck"][];
      maintenance_state: string;
      managed: boolean;
      migration_failure?: string | null;
      migration_state: string;
      minimum_migratable_schema_version: number;
      opened_schema_version?: number | null;
      product_version: string;
      schema_version: number;
      source_revision: string;
      status: string;
      supported_schema_version: number;
      version: string;
    };
    RecentEventsResponse: {
      boundary: components["schemas"]["SessionEventBoundary"];
      events: components["schemas"]["SessionEventEnvelope"][];
    };
    RecoveryAction:
      | "automatic_retry"
      | "resume_goal"
      | "regenerate_with_rewind"
      | "settings"
      | "none";
    ReplayBoundaryEvent: { epoch_id: string; replay_boundary_sequence_id: number };
    ReplayGapEvent: { replay_gap: components["schemas"]["SessionReplayGap"] };
    ResponseTimingSnapshot: {
      cumulative_token_usage?: null | components["schemas"]["TokenUsage"];
      last_response_duration_ms?: number | null;
      last_token_usage?: null | components["schemas"]["TokenUsage"];
      previous_response_duration_ms?: number | null;
      response_durations_ms?: (number | null)[] | null;
      token_usages?: (null | components["schemas"]["TokenUsage"])[] | null;
      unattributed_token_usage?: null | components["schemas"]["TokenUsage"];
    };
    RunFailure: {
      attempt_count: number;
      diagnostic: string;
      http_status?: number | null;
      kind: components["schemas"]["RunFailureKind"];
      partial_output?: components["schemas"]["PartialModelOutput"];
      phase: components["schemas"]["RunFailurePhase"];
      recovery_action: components["schemas"]["RecoveryAction"];
      retry_after_ms?: number | null;
      summary: string;
      transient: boolean;
    };
    RunFailureKind:
      | "transport"
      | "capacity"
      | "authentication"
      | "validation"
      | "configuration"
      | "protocol"
      | "interrupted"
      | "unknown";
    RunFailurePhase: "request" | "response" | "stream" | "decode" | "agent";
    SessionBehavior: "orchestrator" | "direct" | "direct-with-orchestrator";
    SessionClientId: string;
    SessionEvent:
      | { event: components["schemas"]["AgentEvent"]; type: "agent" }
      | {
          prompt_preview: string;
          started_at_epoch_ms: number;
          submitted_user_message?: null | components["schemas"]["SubmittedUserMessageSnapshot"];
          type: "run_started";
        }
      | { duration_ms?: number | null; response: string; type: "run_completed" }
      | {
          failure?: null | components["schemas"]["RunFailure"];
          message: string;
          type: "run_failed";
        }
      | { type: "run_cancelled" }
      | { request: components["schemas"]["PermissionRequest"]; type: "permission_asked" }
      | {
          reply: components["schemas"]["PermissionReply"];
          request_id: string;
          type: "permission_replied";
        }
      | { reason: string; request_id: string; type: "permission_dismissed" }
      | {
          mode: components["schemas"]["PermissionApprovalMode"];
          type: "permission_approval_mode_changed";
        }
      | { session_id: string; type: "snapshot_saved" }
      | { transcript_len: number; type: "transcript_appended" }
      | { transcript_len: number; type: "transcript_reverted" }
      | { command: components["schemas"]["UserCommandSnapshot"]; type: "user_command_updated" };
    SessionEventBoundary: { epoch_id: string; sequence_id: number };
    SessionEventEnvelope: {
      client_id?: null | components["schemas"]["SessionClientId"];
      epoch_id: string;
      event: components["schemas"]["SessionEvent"];
      run_id?: null | components["schemas"]["SessionRunId"];
      sequence_id: number;
      session_id?: string | null;
    };
    SessionForkLink: {
      deleted: boolean;
      session_id: string;
      source_message_idx: number;
      title?: string | null;
    };
    SessionForkOrigin: { deleted?: boolean; session_id: string; title: string };
    SessionFrontendSnapshot: {
      active_compaction?: null | components["schemas"]["ActiveCompactionSnapshot"];
      active_run?: null | components["schemas"]["ActiveRunSnapshot"];
      active_threads?: string[];
      active_user_command?: null | components["schemas"]["UserCommandSnapshot"];
      covered_orchestrator_steering_ids?: number[];
      forks?: components["schemas"]["SessionForkLink"][];
      message_created_at?: (string | null)[];
      messages: components["schemas"]["Message"][];
      metadata: components["schemas"]["SessionMetadata"];
      primary_tool_events?: components["schemas"]["AgentEvent"][];
      response_timing: components["schemas"]["ResponseTimingSnapshot"];
      run_failure?: null | components["schemas"]["RunFailure"];
      sessions: components["schemas"]["SessionSummarySnapshot"][];
      thread_episodes: Record<string, components["schemas"]["EpisodeSnapshot"][]>;
      thread_event_boundary: components["schemas"]["SessionEventBoundary"];
      thread_event_diagnostics?: components["schemas"]["ThreadEventDecodeDiagnostic"][];
      thread_events?: Record<string, components["schemas"]["AgentEvent"][]>;
      thread_steering?: components["schemas"]["ThreadSteeringRecord"][];
      threads: components["schemas"]["ThreadSnapshot"][];
      transcript_recovery_warning?: string | null;
      user_commands?: components["schemas"]["UserCommandSnapshot"][];
      worksets: components["schemas"]["WorksetsSnapshot"];
      workspace: components["schemas"]["WorkspaceSnapshot"];
    };
    SessionLineageKind: "traditional-child" | "managed-orchestrator";
    SessionLineageSnapshot: {
      description: string;
      kind: components["schemas"]["SessionLineageKind"];
      parent_session_id: string;
      root_session_id: string;
    };
    SessionMetadata: {
      agents_md_status: string;
      api_key_env?: string | null;
      backend: string;
      base_url?: string;
      behavior?: components["schemas"]["SessionBehavior"];
      cwd: string;
      extra_headers?: Record<string, string>;
      model: string;
      project_id?: string | null;
      reasoning_effort?: string | null;
      sandbox_status: string;
      session_id?: string | null;
      store_path: string;
      workspace_host_path?: string | null;
    };
    SessionReplayGap: { missing_from_sequence_id: number; missing_to_sequence_id: number };
    SessionRunId: string;
    SessionSnapshotResponse: components["schemas"]["SessionFrontendSnapshot"] & {
      lineage?: null | components["schemas"]["SessionLineageSnapshot"];
      message_cycle?: null | components["schemas"]["MessageCycleMetadata"];
      message_page?: null | components["schemas"]["MessagePageMetadata"];
    };
    SessionSummarySnapshot: {
      backend: string;
      behavior?: components["schemas"]["SessionBehavior"];
      created_at: string;
      cwd: string;
      forked_from?: null | components["schemas"]["SessionForkOrigin"];
      last_user_prompt: string | null;
      model: string;
      model_config_error?: string | null;
      pinned?: boolean;
      presentation_version?: number;
      project_id?: string | null;
      run_count?: number;
      sandboxed: boolean;
      session_id: string;
      sort_order?: number;
      ssh_host: string | null;
      ssh_identity_file?: string | null;
      ssh_port?: number | null;
      title: string | null;
      total_cost_micros?: number | null;
      total_tokens?: number | null;
      updated_at: string;
      visible_message_count: number;
    };
    SubmitPromptResponse: { client_id?: string | null; display_prompt: string; run_id: string };
    SubmittedUserMessageSnapshot: {
      client_id?: null | components["schemas"]["SessionClientId"];
      content: string;
      run_id: components["schemas"]["SessionRunId"];
      submitted_at_epoch_ms: number;
    };
    ThreadEventDecodeDiagnostic: {
      created_at: string;
      error: string;
      id: number;
      thread_name: string;
    };
    ThreadSnapshot: {
      created_at: string;
      episode_count: number;
      latest_action: string | null;
      name: string;
      session_id: string;
      updated_at: string;
    };
    ThreadSteeringRecord: {
      claimed_at?: string | null;
      created_at: string;
      delivered_at?: string | null;
      dispatch_id: string;
      expired_at?: string | null;
      id: number;
      instruction: string;
      session_id: string;
      status: string;
      thread_name: string;
    };
    TokenCostMicros: {
      cache_read?: number;
      cache_write?: number;
      input?: number;
      output?: number;
      total?: number;
    };
    TokenUsage: {
      cache_read_tokens: number;
      cache_write_tokens: number;
      cost?: components["schemas"]["TokenCostMicros"];
      input_tokens: number;
      output_tokens: number;
      reasoning_tokens?: number;
      total_tokens: number;
    };
    ToolCall: { function: components["schemas"]["FunctionCall"]; id: string; type: string };
    ToolCompletionStatus: "success" | "error" | "timed_out" | "cancelled";
    ToolContentPartSchema:
      | { text: string; type: "text" }
      | { image: components["schemas"]["ToolImageSchema"]; type: "image" };
    ToolContentSchema: string | components["schemas"]["ToolContentPartSchema"][];
    ToolImageSchema: { data: string; mime_type: string };
    UiConfiguration: { diagnostic?: string | null; orchestration_enabled: boolean };
    UserCommandSnapshot: {
      command: string;
      created_at_epoch_ms: number;
      cwd?: string | null;
      exit_code?: number | null;
      finished_at_epoch_ms?: number | null;
      message_index?: number | null;
      output_id?: string | null;
      overflowed?: boolean;
      process_started: boolean;
      reason?: string | null;
      request_id: string;
      state: components["schemas"]["UserCommandState"];
      stderr_preview?: string;
      stdout_preview?: string;
      timeout_ms: number;
      truncated?: boolean;
      wall_time_ms?: number | null;
    };
    UserCommandState:
      | "admitted"
      | "executing"
      | "completed"
      | "timed_out"
      | "cancelled"
      | "spawn_failed"
      | "rejected"
      | "interrupted"
      | "outcome_unknown";
    WorksetItemSnapshot: {
      acceptance: string;
      depends_on: string[];
      description: string;
      notes?: string | null;
      position: number;
      role: string;
      scope: string;
      title: string;
      updated_at: string;
    };
    WorksetSnapshot: {
      created_at: string;
      goal: string;
      id: string;
      items: components["schemas"]["WorksetItemSnapshot"][];
      session_id: string;
      status: string;
      summary: string;
      updated_at: string;
      verification_recipe?: string | null;
    };
    WorksetsSnapshot: { error?: string | null; items: components["schemas"]["WorksetSnapshot"][] };
    WorkspaceSnapshot: {
      branch?: string | null;
      changed_files: components["schemas"]["ChangedFileStat"][];
      error?: string | null;
      host_root?: string | null;
      repo_label?: string | null;
      total_additions: number;
      total_deletions: number;
      workspace_display: string;
    };
  };
}

export type ApiSchema<Name extends keyof components["schemas"]> = components["schemas"][Name];
